### PR TITLE
Upgrade to Terraform SDK v2

### PR DESCRIPTION
**Pull request by taiidani**
Sorry for the big PR! There wasn't much I could do to chunk it out. I've tried to itemize every change I made below.

## Breaking Change

As the provider is pre-1.0 I'd advise this be at least a Minor release.

The SDK upgrades forced the following requirements:
* Terraform must be 0.12 or higher
* The `address.address` map is now a block. See the `one password_item_identity` docs/examples diff for the impact.

## Proposed Changes

* Updating all references of `github.com/hashicorp/terraform` to `github.com/hashicorp/terraform-plugin-sdk/v2`.
* Following [Hashicorp's Upgrade Guide](https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html) to deal with the [numerous] changes this requires.
  * Replacing most (but not all) of the `Func` schema functions with `ContextFunc` equivalents as the non-Context variants were deprecated. I've gotta say I love the add of contexts but I'm not a fan of all the changes the `diag.Diagnostics` return type required.
  * One thing I didn't change was the `ValidateFunc` -- Hashicorp said [they'll help ease this transition](https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html#deprecation-of-helper-schema-schemavalidatefunc) in a future release.
  * The `ConflictsWith` blocks in `section.go` were removed. Having them produced `data source onepassword_item_secure_note: ConflictsWith: address. configuration block reference (section.field.string) can only be used with TypeList and MaxItems: 1 configuration blocks` when running `terraform validate`. @anasinnyk I'd love your input on what to do with this; I couldn't figure out a way to get it to work.
* Merging the `examples/` and `examples012/` folders as if this PR is accepted only Terraform 0.12+ will work with the provider.

### CODE REVIEW

**Comment by anasinnyk** [comment]
@taiidani braking changes is it ok for me. We can tag the Major version in the semantic release. But I do not have enough time for testing this. I think we can remove old examples for TF 0.11. It's too old : )
Is these changes support terraform 0.13?

PS: and very very thank you for your job and interest in the project.

**Comment by anasinnyk** [comment]
@taiidani I added one more commit where rewrite validation functions. Can you review it, please?

**Comment by taiidani** [comment]
Excellent! That was one of the areas I took a stab at but reverted because I couldn't quite get it to work. I'll do a more thorough review in a day or so.

>  Is these changes support terraform 0.13?

It's working toward that, yes. It sounds like 0.13 is going to add a number of features around better error handling with providers. I also wanted to get off of the `github.com/hashicorp/terraform` package as they moved everyone to the `github.com/hashicorp/terraform-plugin-sdk` package in 0.12.

**Comment by taiidani** [comment]
@anasinnyk Confirmed that your adds are good!

While testing your validation on a `onepassword_item_login` resource I also found some additional bugs:
* Pre-existing in `master` -- if the `tags` property is omitted, `op` receives an empty `--tags` line and fails. Fixed in https://github.com/anasinnyk/terraform-provider-1password/pull/50/commits/c59b57aebc87122d792551b378a4b6fed801d148
* There were a couple spots where I was allowing fall through of a nil `error` into `diags.FromError(err)`. This causes a nil pointer panic. Yikes! Fixed in https://github.com/anasinnyk/terraform-provider-1password/pull/50/commits/7670ef2b5910370d7055422609186b65242f7a7d

On that note I think the scope of this PR is ready. 0.13 was just released and made the [Terraform Community Providers](https://registry.terraform.io/browse/providers?tier=community) list official, so this should help prepare for it! Although there are a [few more requirements](https://www.terraform.io/docs/registry/providers/publishing.html) it's going to need before it can be fully published.

**Comment by anasinnyk** [comment]
Thanks for a great job @taiidani

**Pull request merged**
